### ISSUE TITLE
Using the Generator without Kinesis

### ISSUE THREAD

**Issue by moe-mahdiani** [boylesoftware/stacy#1]
Hi, I would like to use this solution for generating static pages. However I don't want to use AWS Kinesis. 
I was wondering can I modify 'event' in createHandler function in a way that once a request comes from AWS API Gateway simulate a Kinesis event (which has only one record)?

**Comment by levahim** [comment]
Hi,
There are more than one way to do it following the same principles as in this solution. This solution uses Kinesis, but it could easily be, say, SQS (probably even more appropriate, but requires a little more coding). You need some sort of a queue, however, between then API and the Lamda with the logic to manage the concurrent load on the Lambda function. If that's not a concern (e.g. it's a very small site with rare edits), the API could call the Lambda directly.
Sorry, I haven't reviewed this solution for a while and the AWS tech keeps evolving. There could be better ways to do it these days. I will review it when I need to create another site managed from Contentful.
Best,
Lev.
